website: https://gauravgupta035.github.io
basewebsite: /PD_GenieSpeaks

plugins:
  - jekyll-tabs
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache